### ISSUE TITLE
Proxy Usage

### ISSUE THREAD

**Issue by jo3rg** [Appdynamics/slack-alerting-extension#4]
I've configured a proxy as following in the config.yaml:
`# Slack Webhook URL to post events from AppD to Slack
# https://hooks.slack.com/services/****/***/*****)
webhookUrl: "https://hooks.slack.com/services/some/id/s"

# (optional) Overrides channel and username configured when creating Webhook (channel: "#random")
# Specify if events to be posted to a different channel and with a different identity.
channel: "#alerts"
username: "AppDynamics"

#http timeouts
connectTimeout: 10000
socketTimeout: 10000

#proxy details, provide either proxyUri OR proxyHost and proxyPort.
proxy:
#Host: "10.0.0.1"
#proxyPort: "8080"
 uri: "10.0.0.1:8080"
 #username:
 #password:`

but still receive the following errors in the extension log:
`[main] 09 May 2017 15:57:16,976 ERROR com.appdynamics.extensions.slack.SlackAlertExtension - Error processing an event
Cannot create property=proxy for JavaBean=com.appdynamics.extensions.slack.Configuration@440f4d93
 in 'reader', line 4, column 1:
    webhookUrl: "https://hooks.slack ...
    ^
Unable to find property 'proxy' on class: com.appdynamics.extensions.slack.Configuration
 in 'reader', line 19, column 2:
     uri: "10.0.0.1:8080"
     ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:299)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:332)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:412)
        at com.appdynamics.extensions.yml.YmlReader.read(YmlReader.java:24)
        at com.appdynamics.extensions.yml.YmlReader.readFromFile(YmlReader.java:49)
        at com.appdynamics.extensions.yml.YmlReader.readFromFile(YmlReader.java:40)
        at com.appdynamics.extensions.slack.SlackAlertExtension.main(SlackAlertExtension.java:62)
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'proxy' on class: com.appdynamics.extensions.slack.Configuration
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:132)
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:309)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:240)
        ... 11 more
[main] 09 May 2017 15:57:16,979 ERROR com.appdynamics.extensions.slack.SlackAlertExtension - Slack Extension completed with errors`

Any known issues on that?
Thanks and regards

**Comment by BalakrishnaV** [comment]
Hi,

We haven't faced this issue till now. Could you please email to help@appdynamics.com providing the config.yml and extension log to investigate this further?

Thanks

**Comment by jo3rg** [comment]
Ticket can be closed. Issue has been fixed due to installing the latest version 1.0.3

**Comment by BalakrishnaV** [comment]
Thank You
